// ==============================================================
// Generated by Vitis HLS v2024.1.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module scaffold_fn_float32_mul (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a,
        b,
        float_exception_flags_1_i,
        float_exception_flags_1_o,
        float_exception_flags_1_o_ap_vld,
        countLeadingZerosHigh_address0,
        countLeadingZerosHigh_ce0,
        countLeadingZerosHigh_q0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 22'd1;
parameter    ap_ST_fsm_state2 = 22'd2;
parameter    ap_ST_fsm_state3 = 22'd4;
parameter    ap_ST_fsm_state4 = 22'd8;
parameter    ap_ST_fsm_state5 = 22'd16;
parameter    ap_ST_fsm_state6 = 22'd32;
parameter    ap_ST_fsm_state7 = 22'd64;
parameter    ap_ST_fsm_state8 = 22'd128;
parameter    ap_ST_fsm_state9 = 22'd256;
parameter    ap_ST_fsm_state10 = 22'd512;
parameter    ap_ST_fsm_state11 = 22'd1024;
parameter    ap_ST_fsm_state12 = 22'd2048;
parameter    ap_ST_fsm_state13 = 22'd4096;
parameter    ap_ST_fsm_state14 = 22'd8192;
parameter    ap_ST_fsm_state15 = 22'd16384;
parameter    ap_ST_fsm_state16 = 22'd32768;
parameter    ap_ST_fsm_state17 = 22'd65536;
parameter    ap_ST_fsm_state18 = 22'd131072;
parameter    ap_ST_fsm_state19 = 22'd262144;
parameter    ap_ST_fsm_state20 = 22'd524288;
parameter    ap_ST_fsm_state21 = 22'd1048576;
parameter    ap_ST_fsm_state22 = 22'd2097152;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] a;
input  [31:0] b;
input  [7:0] float_exception_flags_1_i;
output  [7:0] float_exception_flags_1_o;
output   float_exception_flags_1_o_ap_vld;
output  [7:0] countLeadingZerosHigh_address0;
output   countLeadingZerosHigh_ce0;
input  [3:0] countLeadingZerosHigh_q0;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] float_exception_flags_1_o;
reg float_exception_flags_1_o_ap_vld;
reg[31:0] ap_return;

(* fsm_encoding = "none" *) reg   [21:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [8:0] reg_526;
wire   [0:0] icmp_ln1459_fu_614_p2;
wire   [0:0] grp_fu_468_p2;
wire   [0:0] icmp_ln1470_fu_717_p2;
wire   [0:0] and_ln1460_fu_789_p2;
wire   [0:0] grp_fu_473_p2;
reg   [8:0] reg_530;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state18;
wire   [21:0] trunc_ln1445_fu_534_p1;
reg   [21:0] trunc_ln1445_reg_1899;
wire   [21:0] trunc_ln1445_1_fu_538_p1;
reg   [21:0] trunc_ln1445_1_reg_1908;
wire   [22:0] bSig_6_fu_542_p1;
reg   [22:0] bSig_6_reg_1917;
wire   [31:0] zext_ln1448_fu_551_p1;
reg   [31:0] zext_ln1448_reg_1924;
wire   [24:0] zext_ln1448_1_fu_555_p1;
wire   [7:0] aExp_fu_559_p4;
reg   [7:0] aExp_reg_1934;
wire   [8:0] zext_ln1447_fu_569_p1;
wire   [31:0] zext_ln1448_2_fu_581_p1;
reg   [31:0] zext_ln1448_2_reg_1944;
wire   [7:0] bExp_fu_585_p4;
reg   [7:0] bExp_reg_1949;
wire   [8:0] zext_ln1447_1_fu_596_p1;
reg   [8:0] zext_ln1447_1_reg_1955;
wire   [0:0] zSign_fu_608_p2;
reg   [0:0] zSign_reg_1960;
reg   [0:0] icmp_ln1459_reg_1970;
reg   [7:0] float_exception_flags_1_load_reg_1974;
wire   [7:0] or_ln3_fu_634_p3;
reg   [7:0] or_ln3_reg_1981;
reg   [0:0] icmp_ln1469_reg_1999;
wire   [0:0] icmp_ln1478_fu_642_p2;
reg   [0:0] icmp_ln1478_reg_2003;
reg   [0:0] icmp_ln1479_reg_2007;
wire   [0:0] icmp_ln441_fu_658_p2;
reg   [0:0] icmp_ln441_reg_2011;
wire   [0:0] icmp_ln445_fu_688_p2;
reg   [0:0] icmp_ln445_reg_2017;
wire   [0:0] icmp_ln488_3_fu_729_p2;
reg   [0:0] icmp_ln488_3_reg_2030;
wire   [0:0] icmp_ln492_7_fu_743_p2;
reg   [0:0] icmp_ln492_7_reg_2034;
wire   [0:0] icmp_ln488_fu_835_p2;
reg   [0:0] icmp_ln488_reg_2051;
wire   [0:0] icmp_ln492_fu_849_p2;
reg   [0:0] icmp_ln492_reg_2055;
wire   [4:0] trunc_ln1447_fu_921_p1;
reg   [4:0] trunc_ln1447_reg_2060;
wire    ap_CS_fsm_state2;
wire  signed [9:0] sext_ln1447_1_fu_925_p1;
reg  signed [9:0] sext_ln1447_1_reg_2065;
wire   [0:0] icmp_ln1483_fu_929_p2;
reg   [0:0] icmp_ln1483_reg_2070;
wire   [0:0] icmp_ln1484_fu_934_p2;
reg   [0:0] icmp_ln1484_reg_2074;
wire   [0:0] icmp_ln441_1_fu_948_p2;
reg   [0:0] icmp_ln441_1_reg_2078;
wire   [0:0] icmp_ln445_1_fu_976_p2;
reg   [0:0] icmp_ln445_1_reg_2084;
wire   [22:0] bSig_fu_1054_p2;
wire    ap_CS_fsm_state3;
wire  signed [8:0] sext_ln1447_2_fu_1065_p1;
reg   [0:0] tmp_31_reg_2104;
wire   [22:0] trunc_ln1489_fu_1077_p1;
reg   [22:0] trunc_ln1489_reg_2109;
wire   [4:0] add_ln1489_fu_1089_p2;
reg   [4:0] add_ln1489_reg_2114;
wire    ap_CS_fsm_state4;
wire   [9:0] add_ln1488_fu_1094_p2;
reg   [9:0] add_ln1488_reg_2119;
wire   [31:0] trunc_ln141_fu_1129_p1;
reg   [31:0] trunc_ln141_reg_2124;
reg   [0:0] tmp_32_reg_2129;
reg   [30:0] tmp_reg_2134;
reg   [29:0] tmp_33_reg_2139;
reg   [0:0] tmp_34_reg_2144;
wire   [8:0] trunc_ln1493_fu_1222_p1;
wire    ap_CS_fsm_state5;
wire   [31:0] zSig_4_fu_1226_p3;
wire   [6:0] roundBits_fu_1233_p1;
wire   [0:0] icmp_ln763_fu_1237_p2;
reg   [0:0] icmp_ln763_reg_2169;
wire   [0:0] icmp_ln764_fu_1243_p2;
reg   [0:0] icmp_ln764_reg_2173;
wire   [0:0] and_ln765_fu_1269_p2;
reg   [0:0] and_ln765_reg_2177;
wire   [0:0] tmp_38_fu_1275_p3;
reg   [0:0] tmp_38_reg_2181;
wire   [0:0] or_ln771_fu_1295_p2;
reg   [0:0] or_ln771_reg_2185;
wire   [0:0] icmp_ln134_fu_1321_p2;
reg   [0:0] icmp_ln134_reg_2190;
wire   [31:0] zext_ln137_fu_1333_p1;
wire   [31:0] shl_ln135_fu_1352_p2;
reg   [31:0] shl_ln135_reg_2199;
wire   [0:0] trunc_ln135_fu_1358_p1;
reg   [0:0] trunc_ln135_reg_2204;
reg   [30:0] tmp_5_reg_2209;
wire   [0:0] and_ln775_fu_1401_p2;
wire    ap_CS_fsm_state6;
wire   [7:0] select_ln775_fu_1428_p3;
wire   [0:0] icmp_ln779_fu_1435_p2;
reg   [0:0] icmp_ln779_reg_2224;
wire   [24:0] and_ln782_fu_1477_p2;
reg   [24:0] and_ln782_reg_2230;
wire   [7:0] or_ln482_3_fu_1588_p6;
wire    ap_CS_fsm_state8;
wire   [31:0] or_ln737_3_fu_1602_p3;
wire   [31:0] shl_ln737_5_fu_1609_p3;
wire    ap_CS_fsm_state9;
wire   [31:0] shl_ln737_4_fu_1616_p3;
wire    ap_CS_fsm_state10;
wire   [0:0] icmp_ln488_4_fu_1628_p2;
reg   [0:0] icmp_ln488_4_reg_2256;
wire   [0:0] icmp_ln492_9_fu_1642_p2;
reg   [0:0] icmp_ln492_9_reg_2262;
wire   [31:0] a_assign_s_fu_1658_p4;
wire    ap_CS_fsm_state15;
wire   [31:0] b_assign_1_fu_1667_p4;
wire   [0:0] or_ln518_1_fu_1676_p2;
wire   [31:0] select_ln523_1_fu_1693_p3;
wire   [31:0] select_ln532_1_fu_1741_p3;
wire   [31:0] or_ln737_2_fu_1749_p3;
wire    ap_CS_fsm_state16;
wire   [31:0] or_ln4_fu_1756_p3;
wire    ap_CS_fsm_state17;
wire   [0:0] icmp_ln488_2_fu_1768_p2;
reg   [0:0] icmp_ln488_2_reg_2324;
wire   [0:0] icmp_ln492_5_fu_1782_p2;
reg   [0:0] icmp_ln492_5_reg_2330;
wire   [31:0] a_assign_fu_1798_p4;
wire    ap_CS_fsm_state22;
wire   [31:0] b_assign_fu_1807_p4;
wire   [0:0] or_ln518_fu_1816_p2;
wire   [31:0] select_ln523_fu_1833_p3;
wire   [31:0] select_ln532_fu_1881_p3;
wire   [24:0] trunc_ln1448_fu_905_p1;
reg   [24:0] aSig_5_reg_205;
wire  signed [8:0] sext_ln1447_fu_916_p1;
reg  signed [8:0] ap_phi_mux_aExp_5_phi_fu_218_p4;
reg  signed [8:0] aExp_5_reg_215;
reg   [22:0] phi_ln1490_reg_224;
reg  signed [8:0] bExp_5_reg_233;
wire   [31:0] z_fu_1382_p3;
reg   [31:0] ap_phi_mux_z_12_phi_fu_245_p4;
reg   [31:0] z_12_reg_242;
reg   [31:0] ap_phi_mux_empty_phi_fu_254_p6;
reg   [31:0] empty_reg_251;
wire   [6:0] roundBits_3_fu_1390_p1;
reg   [6:0] ap_phi_mux_roundBits_4_phi_fu_266_p6;
reg   [6:0] roundBits_4_reg_263;
reg   [0:0] float_exception_flags_1_flag_3_reg_274;
reg   [7:0] float_exception_flags_1_loc_1_reg_288;
reg   [8:0] zExp_assign_4_reg_299;
reg   [0:0] ap_phi_mux_float_exception_flags_1_flag_5_phi_fu_317_p40;
reg   [0:0] float_exception_flags_1_flag_5_reg_312;
wire   [0:0] and_ln492_fu_1788_p2;
wire   [0:0] and_ln492_7_fu_1793_p2;
wire   [0:0] icmp_ln528_fu_1863_p2;
wire   [0:0] or_ln525_fu_1827_p2;
wire   [0:0] icmp_ln530_fu_1869_p2;
wire   [0:0] and_ln492_9_fu_1648_p2;
wire   [0:0] and_ln492_10_fu_1653_p2;
wire   [0:0] icmp_ln528_1_fu_1723_p2;
wire   [0:0] or_ln525_1_fu_1687_p2;
wire   [0:0] icmp_ln530_1_fu_1729_p2;
wire   [0:0] or_ln779_fu_1512_p2;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln1463_fu_823_p2;
wire   [0:0] icmp_ln1472_fu_777_p2;
reg   [7:0] ap_phi_mux_float_exception_flags_1_new_5_phi_fu_370_p40;
reg   [7:0] float_exception_flags_1_new_5_reg_366;
wire   [7:0] select_ln779_fu_1519_p3;
reg   [31:0] ap_phi_mux_retval_0_phi_fu_420_p40;
reg   [31:0] retval_0_reg_416;
wire   [31:0] add_ln737_fu_1556_p2;
wire   [63:0] zext_ln449_fu_712_p1;
wire   [63:0] zext_ln449_1_fu_1000_p1;
reg    countLeadingZerosHigh_ce0_local;
reg   [7:0] countLeadingZerosHigh_address0_local;
wire   [31:0] mul_ln1491_fu_464_p0;
wire   [31:0] mul_ln1491_fu_464_p1;
wire   [22:0] aSig_6_fu_546_p1;
wire   [0:0] tmp_26_fu_600_p3;
wire   [0:0] tmp_25_fu_573_p3;
wire   [6:0] tmp_s_fu_624_p4;
wire   [6:0] tmp_27_fu_648_p4;
wire   [31:0] shl_ln443_fu_664_p2;
wire   [31:0] select_ln441_2_fu_670_p3;
wire   [7:0] tmp_28_fu_678_p4;
wire   [7:0] tmp_23_fu_694_p4;
wire   [7:0] select_ln445_fu_704_p3;
wire   [31:0] shl_ln488_3_fu_723_p2;
wire   [8:0] grp_fu_478_p4;
wire   [30:0] and_ln492_s_fu_735_p3;
wire   [7:0] trunc_ln1472_fu_749_p1;
wire   [14:0] tmp_2_fu_759_p4;
wire   [7:0] or_ln1472_fu_753_p2;
wire   [22:0] or_ln1_fu_769_p3;
wire   [0:0] icmp_ln1460_2_fu_783_p2;
wire   [7:0] trunc_ln1463_fu_795_p1;
wire   [14:0] tmp_1_fu_805_p4;
wire   [7:0] or_ln1463_fu_799_p2;
wire   [22:0] or_ln_fu_815_p3;
wire   [31:0] shl_ln488_fu_829_p2;
wire   [30:0] and_ln_fu_841_p3;
wire   [4:0] shiftCount_4_fu_862_p3;
wire   [4:0] shiftCount_fu_855_p3;
wire   [4:0] shiftCount_5_fu_869_p3;
wire   [5:0] zext_ln445_fu_876_p1;
wire   [5:0] add_ln731_fu_884_p2;
wire   [5:0] zext_ln731_fu_880_p1;
wire  signed [5:0] shiftCount_6_fu_890_p2;
wire  signed [31:0] sext_ln732_fu_896_p1;
wire   [31:0] aSig_fu_900_p2;
wire   [5:0] aExp_4_fu_910_p2;
wire   [6:0] tmp_29_fu_939_p4;
wire   [31:0] shl_ln443_1_fu_954_p2;
wire   [31:0] select_ln441_3_fu_959_p3;
wire   [7:0] tmp_30_fu_966_p4;
wire   [7:0] tmp_24_fu_982_p4;
wire   [7:0] select_ln445_2_fu_992_p3;
wire   [4:0] shiftCount_8_fu_1012_p3;
wire   [4:0] shiftCount_7_fu_1005_p3;
wire   [4:0] shiftCount_9_fu_1019_p3;
wire   [5:0] zext_ln445_1_fu_1026_p1;
wire   [5:0] add_ln731_2_fu_1034_p2;
wire   [5:0] zext_ln731_1_fu_1030_p1;
wire  signed [5:0] shiftCount_10_fu_1040_p2;
wire  signed [31:0] sext_ln732_1_fu_1046_p1;
wire   [22:0] sext_ln732_1cast_fu_1050_p1;
wire   [5:0] bExp_4_fu_1059_p2;
wire   [4:0] trunc_ln1447_1_fu_1081_p1;
wire  signed [9:0] sext_ln1447_3_fu_1085_p1;
wire   [31:0] aSig_7_fu_1099_p5;
wire   [31:0] bSig_7_fu_1109_p4;
wire   [63:0] mul_ln1491_fu_464_p2;
wire   [0:0] icmp_ln147_fu_1172_p2;
wire   [0:0] or_ln1492_fu_1177_p2;
wire   [6:0] zext_ln1493_1_fu_1201_p1;
wire   [7:0] or_ln5_fu_1204_p3;
wire  signed [10:0] sext_ln1493_fu_1212_p1;
wire  signed [10:0] sext_ln1489_fu_1169_p1;
wire   [10:0] zExp_fu_1216_p2;
wire   [31:0] zSig_fu_1182_p3;
wire   [31:0] zSig_3_fu_1189_p4;
wire   [31:0] add_ln765_fu_1255_p2;
wire   [0:0] icmp_ln765_fu_1249_p2;
wire   [0:0] tmp_35_fu_1261_p3;
wire   [0:0] icmp_ln771_fu_1283_p2;
wire   [0:0] xor_ln771_fu_1289_p2;
wire   [10:0] sub_ln129_fu_1301_p2;
wire   [5:0] tmp_39_fu_1311_p4;
wire   [0:0] z_11_fu_1327_p2;
wire   [31:0] zext_ln129_fu_1307_p1;
wire   [4:0] zext_ln1493_fu_1198_p1;
wire   [4:0] add_ln135_fu_1343_p2;
wire   [31:0] zext_ln135_fu_1348_p1;
wire   [31:0] lshr_ln135_fu_1337_p2;
wire   [0:0] icmp_ln135_fu_1372_p2;
wire   [0:0] or_ln135_fu_1377_p2;
wire   [0:0] icmp_ln775_fu_1395_p2;
wire   [2:0] tmp_40_fu_1406_p4;
wire   [3:0] trunc_ln482_2_fu_1415_p1;
wire   [7:0] or_ln482_4_fu_1418_p4;
wire   [31:0] add_ln781_fu_1441_p2;
wire   [0:0] icmp_ln782_fu_1457_p2;
wire   [1:0] zext_ln782_fu_1463_p1;
wire   [1:0] xor_ln782_fu_1467_p2;
wire   [24:0] trunc_ln_fu_1447_p4;
wire  signed [24:0] sext_ln782_fu_1473_p1;
wire   [1:0] tmp_41_fu_1483_p4;
wire   [4:0] trunc_ln780_fu_1493_p1;
wire   [0:0] xor_ln779_fu_1507_p2;
wire   [7:0] or_ln6_fu_1497_p4;
wire   [0:0] icmp_ln783_fu_1527_p2;
wire   [8:0] select_ln783_fu_1532_p3;
wire   [31:0] shl_ln737_7_fu_1540_p3;
wire   [31:0] or_ln737_5_fu_1548_p4;
wire   [1:0] tmp_36_fu_1569_p4;
wire   [0:0] tmp_37_fu_1578_p3;
wire   [2:0] trunc_ln482_fu_1585_p1;
wire   [31:0] shl_ln488_4_fu_1623_p2;
wire   [8:0] grp_fu_498_p4;
wire   [30:0] and_ln492_1_fu_1634_p3;
wire   [0:0] grp_fu_516_p2;
wire   [0:0] grp_fu_521_p2;
wire   [0:0] xor_ln525_1_fu_1682_p2;
wire   [23:0] shl_ln528_4_fu_1710_p4;
wire   [31:0] shl_ln528_3_fu_1700_p5;
wire  signed [31:0] sext_ln528_1_fu_1719_p1;
wire   [0:0] icmp_ln532_1_fu_1735_p2;
wire   [31:0] shl_ln488_2_fu_1763_p2;
wire   [30:0] and_ln492_8_fu_1774_p3;
wire   [0:0] xor_ln525_fu_1822_p2;
wire   [23:0] shl_ln3_fu_1840_p4;
wire  signed [31:0] sext_ln528_fu_1849_p1;
wire   [31:0] shl_ln528_2_fu_1853_p5;
wire   [0:0] icmp_ln532_fu_1875_p2;
reg   [31:0] ap_return_preg;
reg   [21:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire   [63:0] mul_ln1491_fu_464_p00;
wire   [63:0] mul_ln1491_fu_464_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 22'd1;
#0 ap_return_preg = 32'd0;
end

scaffold_fn_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U1(
    .din0(mul_ln1491_fu_464_p0),
    .din1(mul_ln1491_fu_464_p1),
    .dout(mul_ln1491_fu_464_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_return_preg <= ap_phi_mux_retval_0_phi_fu_420_p40;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fu_468_p2 == 1'd0) & (icmp_ln1459_fu_614_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln1478_fu_642_p2 == 1'd0))) begin
        aExp_5_reg_215 <= zext_ln1447_fu_569_p1;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1478_reg_2003 == 1'd1))) begin
        aExp_5_reg_215 <= sext_ln1447_fu_916_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fu_468_p2 == 1'd0) & (icmp_ln1459_fu_614_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln1478_fu_642_p2 == 1'd0))) begin
        aSig_5_reg_205 <= zext_ln1448_1_fu_555_p1;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1478_reg_2003 == 1'd1))) begin
        aSig_5_reg_205 <= trunc_ln1448_fu_905_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1483_fu_929_p2 == 1'd0))) begin
        bExp_5_reg_233 <= zext_ln1447_1_reg_1955;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln1483_reg_2070 == 1'd1))) begin
        bExp_5_reg_233 <= sext_ln1447_2_fu_1065_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'd0 == and_ln765_fu_1269_p2) & (tmp_38_fu_1275_p3 == 1'd0) & (icmp_ln764_fu_1243_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln763_fu_1237_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln763_fu_1237_p2 == 1'd0)))) begin
        empty_reg_251 <= zSig_4_fu_1226_p3;
    end else if (((tmp_38_reg_2181 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln763_reg_2169 == 1'd1))) begin
        empty_reg_251 <= ap_phi_mux_z_12_phi_fu_245_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'd0 == and_ln765_fu_1269_p2) & (tmp_38_fu_1275_p3 == 1'd0) & (icmp_ln764_fu_1243_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln763_fu_1237_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln763_fu_1237_p2 == 1'd0)))) begin
        float_exception_flags_1_flag_3_reg_274 <= 1'd0;
    end else if (((tmp_38_reg_2181 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln763_reg_2169 == 1'd1))) begin
        float_exception_flags_1_flag_3_reg_274 <= and_ln775_fu_1401_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (((((((((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0)) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) 
    & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))))) begin
        float_exception_flags_1_flag_5_reg_312 <= or_ln779_fu_1512_p2;
    end else if (((1'b1 == ap_CS_fsm_state8) | ((icmp_ln1470_fu_717_p2 == 1'd1) & (grp_fu_468_p2 == 1'd1) & (icmp_ln1459_fu_614_p2 == 1'd0) & (icmp_ln1472_fu_777_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((grp_fu_473_p2 == 1'd1) & (1'd0 == and_ln1460_fu_789_p2) & (icmp_ln1459_fu_614_p2 == 1'd1) & (icmp_ln1463_fu_823_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        float_exception_flags_1_flag_5_reg_312 <= 1'd1;
    end else if ((((1'd0 == and_ln492_9_fu_1648_p2) & (or_ln525_1_fu_1687_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln488_3_reg_2030 == 1'd1)) | ((1'd0 == and_ln492_9_fu_1648_p2) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln488_3_reg_2030 == 1'd0)) | ((1'd1 == and_ln492_9_fu_1648_p2) & (1'd0 == and_ln492_10_fu_1653_p2) & (1'b1 == ap_CS_fsm_state15)) | ((1'b1 == ap_CS_fsm_state15) & (((1'd0 == and_ln492_9_fu_1648_p2) & (icmp_ln530_1_fu_1729_p2 == 1'd0) & (or_ln525_1_fu_1687_p2 == 1'd0) & (icmp_ln528_1_fu_1723_p2 == 1'd0) & (icmp_ln488_3_reg_2030 == 1'd1)) | ((1'd1 == and_ln492_10_fu_1653_p2) & (1'd1 == and_ln492_9_fu_1648_p2) & (icmp_ln530_1_fu_1729_p2 == 1'd0) & (icmp_ln528_1_fu_1723_p2 == 1'd0)))) | ((1'b1 == ap_CS_fsm_state15) & (((1'd0 == and_ln492_9_fu_1648_p2) & (icmp_ln530_1_fu_1729_p2 == 1'd1) & (or_ln525_1_fu_1687_p2 == 1'd0) & (icmp_ln528_1_fu_1723_p2 == 1'd0) & (icmp_ln488_3_reg_2030 == 1'd1)) | ((1'd1 == and_ln492_10_fu_1653_p2) & (1'd1 == and_ln492_9_fu_1648_p2) & (icmp_ln530_1_fu_1729_p2 == 1'd1) & (icmp_ln528_1_fu_1723_p2 
    == 1'd0)))) | ((1'b1 == ap_CS_fsm_state15) & (((1'd0 == and_ln492_9_fu_1648_p2) & (or_ln525_1_fu_1687_p2 == 1'd0) & (icmp_ln528_1_fu_1723_p2 == 1'd1) & (icmp_ln488_3_reg_2030 == 1'd1)) | ((1'd1 == and_ln492_10_fu_1653_p2) & (1'd1 == and_ln492_9_fu_1648_p2) & (icmp_ln528_1_fu_1723_p2 == 1'd1)))))) begin
        float_exception_flags_1_flag_5_reg_312 <= or_ln518_1_fu_1676_p2;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        float_exception_flags_1_flag_5_reg_312 <= 1'd0;
    end else if ((((1'd0 == and_ln492_fu_1788_p2) & (or_ln525_fu_1827_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22) & (icmp_ln488_reg_2051 == 1'd1)) | ((1'd0 == and_ln492_fu_1788_p2) & (1'b1 == ap_CS_fsm_state22) & (icmp_ln488_reg_2051 == 1'd0)) | ((1'd1 == and_ln492_fu_1788_p2) & (1'd0 == and_ln492_7_fu_1793_p2) & (1'b1 == ap_CS_fsm_state22)) | ((1'b1 == ap_CS_fsm_state22) & (((1'd0 == and_ln492_fu_1788_p2) & (icmp_ln530_fu_1869_p2 == 1'd0) & (or_ln525_fu_1827_p2 == 1'd0) & (icmp_ln528_fu_1863_p2 == 1'd0) & (icmp_ln488_reg_2051 == 1'd1)) | ((1'd1 == and_ln492_7_fu_1793_p2) & (1'd1 == and_ln492_fu_1788_p2) & (icmp_ln530_fu_1869_p2 == 1'd0) & (icmp_ln528_fu_1863_p2 == 1'd0)))) | ((1'b1 == ap_CS_fsm_state22) & (((1'd0 == and_ln492_fu_1788_p2) & (icmp_ln530_fu_1869_p2 == 1'd1) & (or_ln525_fu_1827_p2 == 1'd0) & (icmp_ln528_fu_1863_p2 == 1'd0) & (icmp_ln488_reg_2051 == 1'd1)) | ((1'd1 == and_ln492_7_fu_1793_p2) & (1'd1 == and_ln492_fu_1788_p2) & (icmp_ln530_fu_1869_p2 == 1'd1) & (icmp_ln528_fu_1863_p2 == 1'd0)))) | ((1'b1 == ap_CS_fsm_state22) 
    & (((1'd0 == and_ln492_fu_1788_p2) & (or_ln525_fu_1827_p2 == 1'd0) & (icmp_ln528_fu_1863_p2 == 1'd1) & (icmp_ln488_reg_2051 == 1'd1)) | ((1'd1 == and_ln492_7_fu_1793_p2) & (1'd1 == and_ln492_fu_1788_p2) & (icmp_ln528_fu_1863_p2 == 1'd1)))))) begin
        float_exception_flags_1_flag_5_reg_312 <= or_ln518_fu_1816_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'd0 == and_ln765_fu_1269_p2) & (tmp_38_fu_1275_p3 == 1'd0) & (icmp_ln764_fu_1243_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln763_fu_1237_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln763_fu_1237_p2 == 1'd0)))) begin
        float_exception_flags_1_loc_1_reg_288 <= float_exception_flags_1_i;
    end else if (((tmp_38_reg_2181 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln763_reg_2169 == 1'd1))) begin
        float_exception_flags_1_loc_1_reg_288 <= select_ln775_fu_1428_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln1470_fu_717_p2 == 1'd1) & (grp_fu_468_p2 == 1'd1) & (icmp_ln1459_fu_614_p2 == 1'd0) & (icmp_ln1472_fu_777_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((grp_fu_473_p2 == 1'd1) & (1'd0 == and_ln1460_fu_789_p2) & (icmp_ln1459_fu_614_p2 == 1'd1) & (icmp_ln1463_fu_823_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        float_exception_flags_1_new_5_reg_366 <= or_ln3_fu_634_p3;
    end else if (((1'b1 == ap_CS_fsm_state7) & (((((((((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0)) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) 
    & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))))) begin
        float_exception_flags_1_new_5_reg_366 <= select_ln779_fu_1519_p3;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        float_exception_flags_1_new_5_reg_366 <= or_ln482_3_fu_1588_p6;
    end else if ((((1'd0 == and_ln492_9_fu_1648_p2) & (or_ln525_1_fu_1687_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln488_3_reg_2030 == 1'd1)) | ((1'd0 == and_ln492_9_fu_1648_p2) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln488_3_reg_2030 == 1'd0)) | ((1'd1 == and_ln492_9_fu_1648_p2) & (1'd0 == and_ln492_10_fu_1653_p2) & (1'b1 == ap_CS_fsm_state15)) | ((1'd0 == and_ln492_fu_1788_p2) & (or_ln525_fu_1827_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22) & (icmp_ln488_reg_2051 == 1'd1)) | ((1'd0 == and_ln492_fu_1788_p2) & (1'b1 == ap_CS_fsm_state22) & (icmp_ln488_reg_2051 == 1'd0)) | ((1'd1 == and_ln492_fu_1788_p2) & (1'd0 == and_ln492_7_fu_1793_p2) & (1'b1 == ap_CS_fsm_state22)) | ((1'b1 == ap_CS_fsm_state22) & (((1'd0 == and_ln492_fu_1788_p2) & (icmp_ln530_fu_1869_p2 == 1'd0) & (or_ln525_fu_1827_p2 == 1'd0) & (icmp_ln528_fu_1863_p2 == 1'd0) & (icmp_ln488_reg_2051 == 1'd1)) | ((1'd1 == and_ln492_7_fu_1793_p2) & (1'd1 == and_ln492_fu_1788_p2) & (icmp_ln530_fu_1869_p2 == 1'd0) & (icmp_ln528_fu_1863_p2 == 1'd0)))) | ((1'b1 == ap_CS_fsm_state22) 
    & (((1'd0 == and_ln492_fu_1788_p2) & (icmp_ln530_fu_1869_p2 == 1'd1) & (or_ln525_fu_1827_p2 == 1'd0) & (icmp_ln528_fu_1863_p2 == 1'd0) & (icmp_ln488_reg_2051 == 1'd1)) | ((1'd1 == and_ln492_7_fu_1793_p2) & (1'd1 == and_ln492_fu_1788_p2) & (icmp_ln530_fu_1869_p2 == 1'd1) & (icmp_ln528_fu_1863_p2 == 1'd0)))) | ((1'b1 == ap_CS_fsm_state22) & (((1'd0 == and_ln492_fu_1788_p2) & (or_ln525_fu_1827_p2 == 1'd0) & (icmp_ln528_fu_1863_p2 == 1'd1) & (icmp_ln488_reg_2051 == 1'd1)) | ((1'd1 == and_ln492_7_fu_1793_p2) & (1'd1 == and_ln492_fu_1788_p2) & (icmp_ln528_fu_1863_p2 == 1'd1)))) | ((1'b1 == ap_CS_fsm_state15) & (((1'd0 == and_ln492_9_fu_1648_p2) & (icmp_ln530_1_fu_1729_p2 == 1'd0) & (or_ln525_1_fu_1687_p2 == 1'd0) & (icmp_ln528_1_fu_1723_p2 == 1'd0) & (icmp_ln488_3_reg_2030 == 1'd1)) | ((1'd1 == and_ln492_10_fu_1653_p2) & (1'd1 == and_ln492_9_fu_1648_p2) & (icmp_ln530_1_fu_1729_p2 == 1'd0) & (icmp_ln528_1_fu_1723_p2 == 1'd0)))) | ((1'b1 == ap_CS_fsm_state15) & (((1'd0 == and_ln492_9_fu_1648_p2) & (icmp_ln530_1_fu_1729_p2 
    == 1'd1) & (or_ln525_1_fu_1687_p2 == 1'd0) & (icmp_ln528_1_fu_1723_p2 == 1'd0) & (icmp_ln488_3_reg_2030 == 1'd1)) | ((1'd1 == and_ln492_10_fu_1653_p2) & (1'd1 == and_ln492_9_fu_1648_p2) & (icmp_ln530_1_fu_1729_p2 == 1'd1) & (icmp_ln528_1_fu_1723_p2 == 1'd0)))) | ((1'b1 == ap_CS_fsm_state15) & (((1'd0 == and_ln492_9_fu_1648_p2) & (or_ln525_1_fu_1687_p2 == 1'd0) & (icmp_ln528_1_fu_1723_p2 == 1'd1) & (icmp_ln488_3_reg_2030 == 1'd1)) | ((1'd1 == and_ln492_10_fu_1653_p2) & (1'd1 == and_ln492_9_fu_1648_p2) & (icmp_ln528_1_fu_1723_p2 == 1'd1)))))) begin
        float_exception_flags_1_new_5_reg_366 <= or_ln3_reg_1981;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1483_fu_929_p2 == 1'd0))) begin
        phi_ln1490_reg_224 <= bSig_6_reg_1917;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln1483_reg_2070 == 1'd1))) begin
        phi_ln1490_reg_224 <= bSig_fu_1054_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln1470_fu_717_p2 == 1'd1) & (grp_fu_468_p2 == 1'd1) & (icmp_ln1459_fu_614_p2 == 1'd0) & (icmp_ln1472_fu_777_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((grp_fu_473_p2 == 1'd1) & (1'd0 == and_ln1460_fu_789_p2) & (icmp_ln1459_fu_614_p2 == 1'd1) & (icmp_ln1463_fu_823_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        retval_0_reg_416 <= 32'd4290772992;
    end else if (((1'b1 == ap_CS_fsm_state7) & (((((((((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0)) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) 
    & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))))) begin
        retval_0_reg_416 <= add_ln737_fu_1556_p2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        retval_0_reg_416 <= or_ln737_3_fu_1602_p3;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        retval_0_reg_416 <= shl_ln737_5_fu_1609_p3;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        retval_0_reg_416 <= shl_ln737_4_fu_1616_p3;
    end else if (((1'd1 == and_ln492_9_fu_1648_p2) & (1'd0 == and_ln492_10_fu_1653_p2) & (1'b1 == ap_CS_fsm_state15))) begin
        retval_0_reg_416 <= select_ln523_1_fu_1693_p3;
    end else if (((1'b1 == ap_CS_fsm_state15) & (((1'd0 == and_ln492_9_fu_1648_p2) & (icmp_ln530_1_fu_1729_p2 == 1'd0) & (or_ln525_1_fu_1687_p2 == 1'd0) & (icmp_ln528_1_fu_1723_p2 == 1'd0) & (icmp_ln488_3_reg_2030 == 1'd1)) | ((1'd1 == and_ln492_10_fu_1653_p2) & (1'd1 == and_ln492_9_fu_1648_p2) & (icmp_ln530_1_fu_1729_p2 == 1'd0) & (icmp_ln528_1_fu_1723_p2 == 1'd0))))) begin
        retval_0_reg_416 <= select_ln532_1_fu_1741_p3;
    end else if ((((1'd0 == and_ln492_9_fu_1648_p2) & (or_ln525_1_fu_1687_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln488_3_reg_2030 == 1'd1)) | ((1'b1 == ap_CS_fsm_state15) & (((1'd0 == and_ln492_9_fu_1648_p2) & (icmp_ln530_1_fu_1729_p2 == 1'd1) & (or_ln525_1_fu_1687_p2 == 1'd0) & (icmp_ln528_1_fu_1723_p2 == 1'd0) & (icmp_ln488_3_reg_2030 == 1'd1)) | ((1'd1 == and_ln492_10_fu_1653_p2) & (1'd1 == and_ln492_9_fu_1648_p2) & (icmp_ln530_1_fu_1729_p2 == 1'd1) & (icmp_ln528_1_fu_1723_p2 == 1'd0)))))) begin
        retval_0_reg_416 <= a_assign_s_fu_1658_p4;
    end else if ((((1'd0 == and_ln492_9_fu_1648_p2) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln488_3_reg_2030 == 1'd0)) | ((1'b1 == ap_CS_fsm_state15) & (((1'd0 == and_ln492_9_fu_1648_p2) & (or_ln525_1_fu_1687_p2 == 1'd0) & (icmp_ln528_1_fu_1723_p2 == 1'd1) & (icmp_ln488_3_reg_2030 == 1'd1)) | ((1'd1 == and_ln492_10_fu_1653_p2) & (1'd1 == and_ln492_9_fu_1648_p2) & (icmp_ln528_1_fu_1723_p2 == 1'd1)))))) begin
        retval_0_reg_416 <= b_assign_1_fu_1667_p4;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        retval_0_reg_416 <= or_ln737_2_fu_1749_p3;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        retval_0_reg_416 <= or_ln4_fu_1756_p3;
    end else if (((1'd1 == and_ln492_fu_1788_p2) & (1'd0 == and_ln492_7_fu_1793_p2) & (1'b1 == ap_CS_fsm_state22))) begin
        retval_0_reg_416 <= select_ln523_fu_1833_p3;
    end else if (((1'b1 == ap_CS_fsm_state22) & (((1'd0 == and_ln492_fu_1788_p2) & (icmp_ln530_fu_1869_p2 == 1'd0) & (or_ln525_fu_1827_p2 == 1'd0) & (icmp_ln528_fu_1863_p2 == 1'd0) & (icmp_ln488_reg_2051 == 1'd1)) | ((1'd1 == and_ln492_7_fu_1793_p2) & (1'd1 == and_ln492_fu_1788_p2) & (icmp_ln530_fu_1869_p2 == 1'd0) & (icmp_ln528_fu_1863_p2 == 1'd0))))) begin
        retval_0_reg_416 <= select_ln532_fu_1881_p3;
    end else if ((((1'd0 == and_ln492_fu_1788_p2) & (or_ln525_fu_1827_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22) & (icmp_ln488_reg_2051 == 1'd1)) | ((1'b1 == ap_CS_fsm_state22) & (((1'd0 == and_ln492_fu_1788_p2) & (icmp_ln530_fu_1869_p2 == 1'd1) & (or_ln525_fu_1827_p2 == 1'd0) & (icmp_ln528_fu_1863_p2 == 1'd0) & (icmp_ln488_reg_2051 == 1'd1)) | ((1'd1 == and_ln492_7_fu_1793_p2) & (1'd1 == and_ln492_fu_1788_p2) & (icmp_ln530_fu_1869_p2 == 1'd1) & (icmp_ln528_fu_1863_p2 == 1'd0)))))) begin
        retval_0_reg_416 <= a_assign_fu_1798_p4;
    end else if ((((1'd0 == and_ln492_fu_1788_p2) & (1'b1 == ap_CS_fsm_state22) & (icmp_ln488_reg_2051 == 1'd0)) | ((1'b1 == ap_CS_fsm_state22) & (((1'd0 == and_ln492_fu_1788_p2) & (or_ln525_fu_1827_p2 == 1'd0) & (icmp_ln528_fu_1863_p2 == 1'd1) & (icmp_ln488_reg_2051 == 1'd1)) | ((1'd1 == and_ln492_7_fu_1793_p2) & (1'd1 == and_ln492_fu_1788_p2) & (icmp_ln528_fu_1863_p2 == 1'd1)))))) begin
        retval_0_reg_416 <= b_assign_fu_1807_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'd0 == and_ln765_fu_1269_p2) & (tmp_38_fu_1275_p3 == 1'd0) & (icmp_ln764_fu_1243_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln763_fu_1237_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln763_fu_1237_p2 == 1'd0)))) begin
        roundBits_4_reg_263 <= roundBits_fu_1233_p1;
    end else if (((tmp_38_reg_2181 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln763_reg_2169 == 1'd1))) begin
        roundBits_4_reg_263 <= roundBits_3_fu_1390_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'd0 == and_ln765_fu_1269_p2) & (tmp_38_fu_1275_p3 == 1'd0) & (icmp_ln764_fu_1243_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln763_fu_1237_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln763_fu_1237_p2 == 1'd0)))) begin
        zExp_assign_4_reg_299 <= trunc_ln1493_fu_1222_p1;
    end else if (((tmp_38_reg_2181 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln763_reg_2169 == 1'd1))) begin
        zExp_assign_4_reg_299 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln765_fu_1269_p2) & (icmp_ln134_fu_1321_p2 == 1'd0) & (tmp_38_fu_1275_p3 == 1'd1) & (icmp_ln764_fu_1243_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln763_fu_1237_p2 == 1'd1))) begin
        z_12_reg_242 <= zext_ln137_fu_1333_p1;
    end else if (((icmp_ln134_reg_2190 == 1'd1) & (tmp_38_reg_2181 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln763_reg_2169 == 1'd1))) begin
        z_12_reg_242 <= z_fu_1382_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        aExp_reg_1934 <= {{a[30:23]}};
        bExp_reg_1949 <= {{b[30:23]}};
        bSig_6_reg_1917 <= bSig_6_fu_542_p1;
        float_exception_flags_1_load_reg_1974 <= float_exception_flags_1_i;
        icmp_ln1459_reg_1970 <= icmp_ln1459_fu_614_p2;
        icmp_ln1469_reg_1999 <= grp_fu_468_p2;
        icmp_ln1478_reg_2003 <= icmp_ln1478_fu_642_p2;
        icmp_ln1479_reg_2007 <= grp_fu_473_p2;
        icmp_ln441_reg_2011 <= icmp_ln441_fu_658_p2;
        icmp_ln445_reg_2017 <= icmp_ln445_fu_688_p2;
        icmp_ln488_3_reg_2030 <= icmp_ln488_3_fu_729_p2;
        icmp_ln488_reg_2051 <= icmp_ln488_fu_835_p2;
        icmp_ln492_7_reg_2034 <= icmp_ln492_7_fu_743_p2;
        icmp_ln492_reg_2055 <= icmp_ln492_fu_849_p2;
        or_ln3_reg_1981[7 : 1] <= or_ln3_fu_634_p3[7 : 1];
        trunc_ln1445_1_reg_1908 <= trunc_ln1445_1_fu_538_p1;
        trunc_ln1445_reg_1899 <= trunc_ln1445_fu_534_p1;
        zSign_reg_1960 <= zSign_fu_608_p2;
        zext_ln1447_1_reg_1955[7 : 0] <= zext_ln1447_1_fu_596_p1[7 : 0];
        zext_ln1448_2_reg_1944[22 : 0] <= zext_ln1448_2_fu_581_p1[22 : 0];
        zext_ln1448_reg_1924[22 : 0] <= zext_ln1448_fu_551_p1[22 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln1488_reg_2119 <= add_ln1488_fu_1094_p2;
        add_ln1489_reg_2114 <= add_ln1489_fu_1089_p2;
        tmp_32_reg_2129 <= mul_ln1491_fu_464_p2[32'd32];
        tmp_33_reg_2139 <= {{mul_ln1491_fu_464_p2[62:33]}};
        tmp_34_reg_2144 <= mul_ln1491_fu_464_p2[32'd62];
        tmp_reg_2134 <= {{mul_ln1491_fu_464_p2[63:33]}};
        trunc_ln141_reg_2124 <= trunc_ln141_fu_1129_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        and_ln765_reg_2177 <= and_ln765_fu_1269_p2;
        icmp_ln134_reg_2190 <= icmp_ln134_fu_1321_p2;
        icmp_ln763_reg_2169 <= icmp_ln763_fu_1237_p2;
        icmp_ln764_reg_2173 <= icmp_ln764_fu_1243_p2;
        or_ln771_reg_2185 <= or_ln771_fu_1295_p2;
        shl_ln135_reg_2199 <= shl_ln135_fu_1352_p2;
        tmp_38_reg_2181 <= zExp_fu_1216_p2[32'd10];
        tmp_5_reg_2209 <= {{lshr_ln135_fu_1337_p2[31:1]}};
        trunc_ln135_reg_2204 <= trunc_ln135_fu_1358_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        and_ln782_reg_2230 <= and_ln782_fu_1477_p2;
        icmp_ln779_reg_2224 <= icmp_ln779_fu_1435_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln1483_reg_2070 <= icmp_ln1483_fu_929_p2;
        icmp_ln1484_reg_2074 <= icmp_ln1484_fu_934_p2;
        icmp_ln441_1_reg_2078 <= icmp_ln441_1_fu_948_p2;
        icmp_ln445_1_reg_2084 <= icmp_ln445_1_fu_976_p2;
        sext_ln1447_1_reg_2065 <= sext_ln1447_1_fu_925_p1;
        trunc_ln1447_reg_2060 <= trunc_ln1447_fu_921_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        icmp_ln488_2_reg_2324 <= icmp_ln488_2_fu_1768_p2;
        icmp_ln492_5_reg_2330 <= icmp_ln492_5_fu_1782_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        icmp_ln488_4_reg_2256 <= icmp_ln488_4_fu_1628_p2;
        icmp_ln492_9_reg_2262 <= icmp_ln492_9_fu_1642_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln1470_fu_717_p2 == 1'd0) & (grp_fu_468_p2 == 1'd1) & (icmp_ln1459_fu_614_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state1) & (((grp_fu_473_p2 == 1'd0) & (icmp_ln1459_fu_614_p2 == 1'd1)) | ((1'd1 == and_ln1460_fu_789_p2) & (icmp_ln1459_fu_614_p2 == 1'd1)))))) begin
        reg_526 <= {{a[31:23]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state11))) begin
        reg_530 <= {{b[31:23]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_31_reg_2104 <= aSig_5_reg_205[32'd24];
        trunc_ln1489_reg_2109 <= trunc_ln1489_fu_1077_p1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1478_reg_2003 == 1'd1))) begin
        ap_phi_mux_aExp_5_phi_fu_218_p4 = sext_ln1447_fu_916_p1;
    end else begin
        ap_phi_mux_aExp_5_phi_fu_218_p4 = aExp_5_reg_215;
    end
end

always @ (*) begin
    if (((tmp_38_reg_2181 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln763_reg_2169 == 1'd1))) begin
        ap_phi_mux_empty_phi_fu_254_p6 = ap_phi_mux_z_12_phi_fu_245_p4;
    end else begin
        ap_phi_mux_empty_phi_fu_254_p6 = empty_reg_251;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (((((((((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0)) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) 
    & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))))) begin
        ap_phi_mux_float_exception_flags_1_flag_5_phi_fu_317_p40 = or_ln779_fu_1512_p2;
    end else begin
        ap_phi_mux_float_exception_flags_1_flag_5_phi_fu_317_p40 = float_exception_flags_1_flag_5_reg_312;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (((((((((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0)) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) 
    & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))))) begin
        ap_phi_mux_float_exception_flags_1_new_5_phi_fu_370_p40 = select_ln779_fu_1519_p3;
    end else begin
        ap_phi_mux_float_exception_flags_1_new_5_phi_fu_370_p40 = float_exception_flags_1_new_5_reg_366;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (((((((((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0)) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1479_reg_2007 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1484_reg_2074 == 1'd0) 
    & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((1'd0 == and_ln765_reg_2177) & (icmp_ln764_reg_2173 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))) | ((icmp_ln763_reg_2169 == 1'd0) & (icmp_ln1483_reg_2070 == 1'd0) & (icmp_ln1478_reg_2003 == 1'd0) & (icmp_ln1469_reg_1999 == 1'd0) & (icmp_ln1459_reg_1970 == 1'd0))))) begin
        ap_phi_mux_retval_0_phi_fu_420_p40 = add_ln737_fu_1556_p2;
    end else begin
        ap_phi_mux_retval_0_phi_fu_420_p40 = retval_0_reg_416;
    end
end

always @ (*) begin
    if (((tmp_38_reg_2181 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln763_reg_2169 == 1'd1))) begin
        ap_phi_mux_roundBits_4_phi_fu_266_p6 = roundBits_3_fu_1390_p1;
    end else begin
        ap_phi_mux_roundBits_4_phi_fu_266_p6 = roundBits_4_reg_263;
    end
end

always @ (*) begin
    if (((icmp_ln134_reg_2190 == 1'd1) & (tmp_38_reg_2181 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln763_reg_2169 == 1'd1))) begin
        ap_phi_mux_z_12_phi_fu_245_p4 = z_fu_1382_p3;
    end else begin
        ap_phi_mux_z_12_phi_fu_245_p4 = z_12_reg_242;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_return = ap_phi_mux_retval_0_phi_fu_420_p40;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        countLeadingZerosHigh_address0_local = zext_ln449_1_fu_1000_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        countLeadingZerosHigh_address0_local = zext_ln449_fu_712_p1;
    end else begin
        countLeadingZerosHigh_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        countLeadingZerosHigh_ce0_local = 1'b1;
    end else begin
        countLeadingZerosHigh_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_float_exception_flags_1_flag_5_phi_fu_317_p40 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        float_exception_flags_1_o = ap_phi_mux_float_exception_flags_1_new_5_phi_fu_370_p40;
    end else begin
        float_exception_flags_1_o = float_exception_flags_1_i;
    end
end

always @ (*) begin
    if (((ap_phi_mux_float_exception_flags_1_flag_5_phi_fu_317_p40 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        float_exception_flags_1_o_ap_vld = 1'b1;
    end else begin
        float_exception_flags_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((grp_fu_473_p2 == 1'd1) & (1'd0 == and_ln1460_fu_789_p2) & (icmp_ln1459_fu_614_p2 == 1'd1) & (icmp_ln1463_fu_823_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((grp_fu_473_p2 == 1'd0) & (icmp_ln1459_fu_614_p2 == 1'd1)) | ((1'd1 == and_ln1460_fu_789_p2) & (icmp_ln1459_fu_614_p2 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else if (((icmp_ln1470_fu_717_p2 == 1'd1) & (grp_fu_468_p2 == 1'd1) & (icmp_ln1459_fu_614_p2 == 1'd0) & (icmp_ln1472_fu_777_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln1470_fu_717_p2 == 1'd1) & (grp_fu_468_p2 == 1'd1) & (icmp_ln1459_fu_614_p2 == 1'd0) & (icmp_ln1472_fu_777_p2 == 1'd1)) | ((grp_fu_473_p2 == 1'd1) & (1'd0 == and_ln1460_fu_789_p2) & (icmp_ln1459_fu_614_p2 == 1'd1) & (icmp_ln1463_fu_823_p2 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if (((icmp_ln1470_fu_717_p2 == 1'd0) & (grp_fu_468_p2 == 1'd1) & (icmp_ln1459_fu_614_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if (((grp_fu_473_p2 == 1'd1) & (grp_fu_468_p2 == 1'd0) & (icmp_ln1459_fu_614_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln1478_fu_642_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((grp_fu_473_p2 == 1'd0) & (grp_fu_468_p2 == 1'd0) & (icmp_ln1459_fu_614_p2 == 1'd0)) | ((grp_fu_468_p2 == 1'd0) & (icmp_ln1459_fu_614_p2 == 1'd0) & (icmp_ln1478_fu_642_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1484_fu_934_p2 == 1'd1) & (icmp_ln1483_fu_929_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (((icmp_ln764_fu_1243_p2 == 1'd1) & (icmp_ln763_fu_1237_p2 == 1'd1)) | ((1'd1 == and_ln765_fu_1269_p2) & (icmp_ln763_fu_1237_p2 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign aExp_4_fu_910_p2 = ($signed(6'd1) - $signed(shiftCount_6_fu_890_p2));

assign aExp_fu_559_p4 = {{a[30:23]}};

assign aSig_6_fu_546_p1 = a[22:0];

assign aSig_7_fu_1099_p5 = {{{{tmp_31_reg_2104}, {1'd1}}, {trunc_ln1489_reg_2109}}, {7'd0}};

assign aSig_fu_900_p2 = zext_ln1448_reg_1924 << sext_ln732_fu_896_p1;

assign a_assign_fu_1798_p4 = {{{reg_526}, {1'd1}}, {trunc_ln1445_1_reg_1908}};

assign a_assign_s_fu_1658_p4 = {{{reg_526}, {1'd1}}, {trunc_ln1445_1_reg_1908}};

assign add_ln135_fu_1343_p2 = (zext_ln1493_fu_1198_p1 + add_ln1489_reg_2114);

assign add_ln1488_fu_1094_p2 = ($signed(sext_ln1447_3_fu_1085_p1) + $signed(sext_ln1447_1_reg_2065));

assign add_ln1489_fu_1089_p2 = (trunc_ln1447_1_fu_1081_p1 + trunc_ln1447_reg_2060);

assign add_ln731_2_fu_1034_p2 = ($signed(zext_ln445_1_fu_1026_p1) + $signed(6'd56));

assign add_ln731_fu_884_p2 = ($signed(zext_ln445_fu_876_p1) + $signed(6'd56));

assign add_ln737_fu_1556_p2 = (shl_ln737_7_fu_1540_p3 + or_ln737_5_fu_1548_p4);

assign add_ln765_fu_1255_p2 = (zSig_4_fu_1226_p3 + 32'd64);

assign add_ln781_fu_1441_p2 = (ap_phi_mux_empty_phi_fu_254_p6 + 32'd64);

assign and_ln1460_fu_789_p2 = (icmp_ln1460_2_fu_783_p2 & grp_fu_468_p2);

assign and_ln492_10_fu_1653_p2 = (icmp_ln492_9_reg_2262 & grp_fu_521_p2);

assign and_ln492_1_fu_1634_p3 = {{grp_fu_498_p4}, {22'd0}};

assign and_ln492_7_fu_1793_p2 = (icmp_ln492_5_reg_2330 & grp_fu_521_p2);

assign and_ln492_8_fu_1774_p3 = {{grp_fu_498_p4}, {22'd0}};

assign and_ln492_9_fu_1648_p2 = (icmp_ln492_7_reg_2034 & grp_fu_516_p2);

assign and_ln492_fu_1788_p2 = (icmp_ln492_reg_2055 & grp_fu_516_p2);

assign and_ln492_s_fu_735_p3 = {{grp_fu_478_p4}, {22'd0}};

assign and_ln765_fu_1269_p2 = (tmp_35_fu_1261_p3 & icmp_ln765_fu_1249_p2);

assign and_ln775_fu_1401_p2 = (or_ln771_reg_2185 & icmp_ln775_fu_1395_p2);

assign and_ln782_fu_1477_p2 = (trunc_ln_fu_1447_p4 & sext_ln782_fu_1473_p1);

assign and_ln_fu_841_p3 = {{grp_fu_478_p4}, {22'd0}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign bExp_4_fu_1059_p2 = ($signed(6'd1) - $signed(shiftCount_10_fu_1040_p2));

assign bExp_fu_585_p4 = {{b[30:23]}};

assign bSig_6_fu_542_p1 = b[22:0];

assign bSig_7_fu_1109_p4 = {{{{1'd1}, {phi_ln1490_reg_224}}}, {8'd0}};

assign bSig_fu_1054_p2 = bSig_6_reg_1917 << sext_ln732_1cast_fu_1050_p1;

assign b_assign_1_fu_1667_p4 = {{{reg_530}, {1'd1}}, {trunc_ln1445_reg_1899}};

assign b_assign_fu_1807_p4 = {{{reg_530}, {1'd1}}, {trunc_ln1445_reg_1899}};

assign countLeadingZerosHigh_address0 = countLeadingZerosHigh_address0_local;

assign countLeadingZerosHigh_ce0 = countLeadingZerosHigh_ce0_local;

assign grp_fu_468_p2 = ((bExp_fu_585_p4 == 8'd255) ? 1'b1 : 1'b0);

assign grp_fu_473_p2 = ((aSig_6_fu_546_p1 == 23'd0) ? 1'b1 : 1'b0);

assign grp_fu_478_p4 = {{a[30:22]}};

assign grp_fu_498_p4 = {{b[30:22]}};

assign grp_fu_516_p2 = ((trunc_ln1445_1_reg_1908 != 22'd0) ? 1'b1 : 1'b0);

assign grp_fu_521_p2 = ((trunc_ln1445_reg_1899 != 22'd0) ? 1'b1 : 1'b0);

assign icmp_ln134_fu_1321_p2 = ((tmp_39_fu_1311_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln135_fu_1372_p2 = ((shl_ln135_reg_2199 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln1459_fu_614_p2 = ((aExp_fu_559_p4 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln1460_2_fu_783_p2 = ((bSig_6_fu_542_p1 != 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln1463_fu_823_p2 = ((or_ln_fu_815_p3 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln1470_fu_717_p2 = ((bSig_6_fu_542_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln1472_fu_777_p2 = ((or_ln1_fu_769_p3 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln1478_fu_642_p2 = ((aExp_fu_559_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln147_fu_1172_p2 = ((trunc_ln141_reg_2124 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln1483_fu_929_p2 = ((bExp_reg_1949 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln1484_fu_934_p2 = ((bSig_6_reg_1917 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln441_1_fu_948_p2 = ((tmp_29_fu_939_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln441_fu_658_p2 = ((tmp_27_fu_648_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln445_1_fu_976_p2 = ((tmp_30_fu_966_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln445_fu_688_p2 = ((tmp_28_fu_678_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln488_2_fu_1768_p2 = ((shl_ln488_2_fu_1763_p2 > 32'd4278190080) ? 1'b1 : 1'b0);

assign icmp_ln488_3_fu_729_p2 = ((shl_ln488_3_fu_723_p2 > 32'd4278190080) ? 1'b1 : 1'b0);

assign icmp_ln488_4_fu_1628_p2 = ((shl_ln488_4_fu_1623_p2 > 32'd4278190080) ? 1'b1 : 1'b0);

assign icmp_ln488_fu_835_p2 = ((shl_ln488_fu_829_p2 > 32'd4278190080) ? 1'b1 : 1'b0);

assign icmp_ln492_5_fu_1782_p2 = ((and_ln492_8_fu_1774_p3 == 31'd2139095040) ? 1'b1 : 1'b0);

assign icmp_ln492_7_fu_743_p2 = ((and_ln492_s_fu_735_p3 == 31'd2139095040) ? 1'b1 : 1'b0);

assign icmp_ln492_9_fu_1642_p2 = ((and_ln492_1_fu_1634_p3 == 31'd2139095040) ? 1'b1 : 1'b0);

assign icmp_ln492_fu_849_p2 = ((and_ln_fu_841_p3 == 31'd2139095040) ? 1'b1 : 1'b0);

assign icmp_ln528_1_fu_1723_p2 = ((shl_ln528_3_fu_1700_p5 < sext_ln528_1_fu_1719_p1) ? 1'b1 : 1'b0);

assign icmp_ln528_fu_1863_p2 = ((sext_ln528_fu_1849_p1 < shl_ln528_2_fu_1853_p5) ? 1'b1 : 1'b0);

assign icmp_ln530_1_fu_1729_p2 = ((sext_ln528_1_fu_1719_p1 < shl_ln528_3_fu_1700_p5) ? 1'b1 : 1'b0);

assign icmp_ln530_fu_1869_p2 = ((shl_ln528_2_fu_1853_p5 < sext_ln528_fu_1849_p1) ? 1'b1 : 1'b0);

assign icmp_ln532_1_fu_1735_p2 = ((a_assign_s_fu_1658_p4 < b_assign_1_fu_1667_p4) ? 1'b1 : 1'b0);

assign icmp_ln532_fu_1875_p2 = ((a_assign_fu_1798_p4 < b_assign_fu_1807_p4) ? 1'b1 : 1'b0);

assign icmp_ln763_fu_1237_p2 = ((zExp_fu_1216_p2 > 11'd252) ? 1'b1 : 1'b0);

assign icmp_ln764_fu_1243_p2 = (($signed(zExp_fu_1216_p2) > $signed(11'd253)) ? 1'b1 : 1'b0);

assign icmp_ln765_fu_1249_p2 = ((zExp_fu_1216_p2 == 11'd253) ? 1'b1 : 1'b0);

assign icmp_ln771_fu_1283_p2 = (($signed(zExp_fu_1216_p2) < $signed(11'd2047)) ? 1'b1 : 1'b0);

assign icmp_ln775_fu_1395_p2 = ((roundBits_3_fu_1390_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln779_fu_1435_p2 = ((ap_phi_mux_roundBits_4_phi_fu_266_p6 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln782_fu_1457_p2 = ((ap_phi_mux_roundBits_4_phi_fu_266_p6 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln783_fu_1527_p2 = ((and_ln782_reg_2230 == 25'd0) ? 1'b1 : 1'b0);

assign lshr_ln135_fu_1337_p2 = zSig_4_fu_1226_p3 >> zext_ln129_fu_1307_p1;

assign mul_ln1491_fu_464_p0 = mul_ln1491_fu_464_p00;

assign mul_ln1491_fu_464_p00 = bSig_7_fu_1109_p4;

assign mul_ln1491_fu_464_p1 = mul_ln1491_fu_464_p10;

assign mul_ln1491_fu_464_p10 = aSig_7_fu_1099_p5;

assign or_ln135_fu_1377_p2 = (trunc_ln135_reg_2204 | icmp_ln135_fu_1372_p2);

assign or_ln1463_fu_799_p2 = (trunc_ln1463_fu_795_p1 | bExp_fu_585_p4);

assign or_ln1472_fu_753_p2 = (trunc_ln1472_fu_749_p1 | aExp_fu_559_p4);

assign or_ln1492_fu_1177_p2 = (tmp_32_reg_2129 | icmp_ln147_fu_1172_p2);

assign or_ln1_fu_769_p3 = {{tmp_2_fu_759_p4}, {or_ln1472_fu_753_p2}};

assign or_ln3_fu_634_p3 = {{tmp_s_fu_624_p4}, {1'd1}};

assign or_ln482_3_fu_1588_p6 = {{{{{tmp_36_fu_1569_p4}, {1'd1}}, {tmp_37_fu_1578_p3}}, {1'd1}}, {trunc_ln482_fu_1585_p1}};

assign or_ln482_4_fu_1418_p4 = {{{tmp_40_fu_1406_p4}, {1'd1}}, {trunc_ln482_2_fu_1415_p1}};

assign or_ln4_fu_1756_p3 = {{zSign_reg_1960}, {31'd2139095040}};

assign or_ln518_1_fu_1676_p2 = (and_ln492_9_fu_1648_p2 | and_ln492_10_fu_1653_p2);

assign or_ln518_fu_1816_p2 = (and_ln492_fu_1788_p2 | and_ln492_7_fu_1793_p2);

assign or_ln525_1_fu_1687_p2 = (xor_ln525_1_fu_1682_p2 | and_ln492_10_fu_1653_p2);

assign or_ln525_fu_1827_p2 = (xor_ln525_fu_1822_p2 | and_ln492_7_fu_1793_p2);

assign or_ln5_fu_1204_p3 = {{1'd1}, {zext_ln1493_1_fu_1201_p1}};

assign or_ln6_fu_1497_p4 = {{{tmp_41_fu_1483_p4}, {1'd1}}, {trunc_ln780_fu_1493_p1}};

assign or_ln737_2_fu_1749_p3 = {{zSign_reg_1960}, {31'd2139095040}};

assign or_ln737_3_fu_1602_p3 = {{zSign_reg_1960}, {31'd2139095040}};

assign or_ln737_5_fu_1548_p4 = {{{zSign_reg_1960}, {6'd0}}, {and_ln782_reg_2230}};

assign or_ln771_fu_1295_p2 = (xor_ln771_fu_1289_p2 | icmp_ln771_fu_1283_p2);

assign or_ln779_fu_1512_p2 = (xor_ln779_fu_1507_p2 | float_exception_flags_1_flag_3_reg_274);

assign or_ln_fu_815_p3 = {{tmp_1_fu_805_p4}, {or_ln1463_fu_799_p2}};

assign roundBits_3_fu_1390_p1 = ap_phi_mux_z_12_phi_fu_245_p4[6:0];

assign roundBits_fu_1233_p1 = zSig_4_fu_1226_p3[6:0];

assign select_ln441_2_fu_670_p3 = ((icmp_ln441_fu_658_p2[0:0] == 1'b1) ? shl_ln443_fu_664_p2 : zext_ln1448_fu_551_p1);

assign select_ln441_3_fu_959_p3 = ((icmp_ln441_1_fu_948_p2[0:0] == 1'b1) ? shl_ln443_1_fu_954_p2 : zext_ln1448_2_reg_1944);

assign select_ln445_2_fu_992_p3 = ((icmp_ln445_1_fu_976_p2[0:0] == 1'b1) ? tmp_24_fu_982_p4 : tmp_30_fu_966_p4);

assign select_ln445_fu_704_p3 = ((icmp_ln445_fu_688_p2[0:0] == 1'b1) ? tmp_23_fu_694_p4 : tmp_28_fu_678_p4);

assign select_ln523_1_fu_1693_p3 = ((icmp_ln488_4_reg_2256[0:0] == 1'b1) ? b_assign_1_fu_1667_p4 : a_assign_s_fu_1658_p4);

assign select_ln523_fu_1833_p3 = ((icmp_ln488_2_reg_2324[0:0] == 1'b1) ? b_assign_fu_1807_p4 : a_assign_fu_1798_p4);

assign select_ln532_1_fu_1741_p3 = ((icmp_ln532_1_fu_1735_p2[0:0] == 1'b1) ? a_assign_s_fu_1658_p4 : b_assign_1_fu_1667_p4);

assign select_ln532_fu_1881_p3 = ((icmp_ln532_fu_1875_p2[0:0] == 1'b1) ? a_assign_fu_1798_p4 : b_assign_fu_1807_p4);

assign select_ln775_fu_1428_p3 = ((and_ln775_fu_1401_p2[0:0] == 1'b1) ? or_ln482_4_fu_1418_p4 : float_exception_flags_1_i);

assign select_ln779_fu_1519_p3 = ((icmp_ln779_reg_2224[0:0] == 1'b1) ? float_exception_flags_1_loc_1_reg_288 : or_ln6_fu_1497_p4);

assign select_ln783_fu_1532_p3 = ((icmp_ln783_fu_1527_p2[0:0] == 1'b1) ? 9'd0 : zExp_assign_4_reg_299);

assign sext_ln1447_1_fu_925_p1 = ap_phi_mux_aExp_5_phi_fu_218_p4;

assign sext_ln1447_2_fu_1065_p1 = $signed(bExp_4_fu_1059_p2);

assign sext_ln1447_3_fu_1085_p1 = bExp_5_reg_233;

assign sext_ln1447_fu_916_p1 = $signed(aExp_4_fu_910_p2);

assign sext_ln1489_fu_1169_p1 = $signed(add_ln1488_reg_2119);

assign sext_ln1493_fu_1212_p1 = $signed(or_ln5_fu_1204_p3);

assign sext_ln528_1_fu_1719_p1 = $signed(shl_ln528_4_fu_1710_p4);

assign sext_ln528_fu_1849_p1 = $signed(shl_ln3_fu_1840_p4);

assign sext_ln732_1_fu_1046_p1 = shiftCount_10_fu_1040_p2;

assign sext_ln732_1cast_fu_1050_p1 = sext_ln732_1_fu_1046_p1[22:0];

assign sext_ln732_fu_896_p1 = shiftCount_6_fu_890_p2;

assign sext_ln782_fu_1473_p1 = $signed(xor_ln782_fu_1467_p2);

assign shiftCount_10_fu_1040_p2 = (add_ln731_2_fu_1034_p2 + zext_ln731_1_fu_1030_p1);

assign shiftCount_4_fu_862_p3 = ((icmp_ln441_reg_2011[0:0] == 1'b1) ? 5'd24 : 5'd8);

assign shiftCount_5_fu_869_p3 = ((icmp_ln445_reg_2017[0:0] == 1'b1) ? shiftCount_4_fu_862_p3 : shiftCount_fu_855_p3);

assign shiftCount_6_fu_890_p2 = (add_ln731_fu_884_p2 + zext_ln731_fu_880_p1);

assign shiftCount_7_fu_1005_p3 = ((icmp_ln441_1_reg_2078[0:0] == 1'b1) ? 5'd16 : 5'd0);

assign shiftCount_8_fu_1012_p3 = ((icmp_ln441_1_reg_2078[0:0] == 1'b1) ? 5'd24 : 5'd8);

assign shiftCount_9_fu_1019_p3 = ((icmp_ln445_1_reg_2084[0:0] == 1'b1) ? shiftCount_8_fu_1012_p3 : shiftCount_7_fu_1005_p3);

assign shiftCount_fu_855_p3 = ((icmp_ln441_reg_2011[0:0] == 1'b1) ? 5'd16 : 5'd0);

assign shl_ln135_fu_1352_p2 = zSig_4_fu_1226_p3 << zext_ln135_fu_1348_p1;

assign shl_ln3_fu_1840_p4 = {{{{1'd1}, {trunc_ln1445_1_reg_1908}}}, {1'd0}};

assign shl_ln443_1_fu_954_p2 = b << 32'd16;

assign shl_ln443_fu_664_p2 = a << 32'd16;

assign shl_ln488_2_fu_1763_p2 = b << 32'd1;

assign shl_ln488_3_fu_723_p2 = a << 32'd1;

assign shl_ln488_4_fu_1623_p2 = b << 32'd1;

assign shl_ln488_fu_829_p2 = a << 32'd1;

assign shl_ln528_2_fu_1853_p5 = {{{{bExp_reg_1949}, {1'd1}}, {trunc_ln1445_reg_1899}}, {1'd0}};

assign shl_ln528_3_fu_1700_p5 = {{{{aExp_reg_1934}, {1'd1}}, {trunc_ln1445_1_reg_1908}}, {1'd0}};

assign shl_ln528_4_fu_1710_p4 = {{{{1'd1}, {trunc_ln1445_reg_1899}}}, {1'd0}};

assign shl_ln737_4_fu_1616_p3 = {{zSign_reg_1960}, {31'd0}};

assign shl_ln737_5_fu_1609_p3 = {{zSign_reg_1960}, {31'd0}};

assign shl_ln737_7_fu_1540_p3 = {{select_ln783_fu_1532_p3}, {23'd0}};

assign sub_ln129_fu_1301_p2 = (11'd0 - zExp_fu_1216_p2);

assign tmp_1_fu_805_p4 = {{b[22:8]}};

assign tmp_23_fu_694_p4 = {{select_ln441_2_fu_670_p3[23:16]}};

assign tmp_24_fu_982_p4 = {{select_ln441_3_fu_959_p3[23:16]}};

assign tmp_25_fu_573_p3 = a[32'd31];

assign tmp_26_fu_600_p3 = b[32'd31];

assign tmp_27_fu_648_p4 = {{a[22:16]}};

assign tmp_28_fu_678_p4 = {{select_ln441_2_fu_670_p3[31:24]}};

assign tmp_29_fu_939_p4 = {{b[22:16]}};

assign tmp_2_fu_759_p4 = {{a[22:8]}};

assign tmp_30_fu_966_p4 = {{select_ln441_3_fu_959_p3[31:24]}};

assign tmp_35_fu_1261_p3 = add_ln765_fu_1255_p2[32'd31];

assign tmp_36_fu_1569_p4 = {{float_exception_flags_1_load_reg_1974[7:6]}};

assign tmp_37_fu_1578_p3 = float_exception_flags_1_load_reg_1974[32'd4];

assign tmp_38_fu_1275_p3 = zExp_fu_1216_p2[32'd10];

assign tmp_39_fu_1311_p4 = {{sub_ln129_fu_1301_p2[10:5]}};

assign tmp_40_fu_1406_p4 = {{float_exception_flags_1_i[7:5]}};

assign tmp_41_fu_1483_p4 = {{float_exception_flags_1_loc_1_reg_288[7:6]}};

assign tmp_s_fu_624_p4 = {{float_exception_flags_1_i[7:1]}};

assign trunc_ln135_fu_1358_p1 = lshr_ln135_fu_1337_p2[0:0];

assign trunc_ln141_fu_1129_p1 = mul_ln1491_fu_464_p2[31:0];

assign trunc_ln1445_1_fu_538_p1 = a[21:0];

assign trunc_ln1445_fu_534_p1 = b[21:0];

assign trunc_ln1447_1_fu_1081_p1 = bExp_5_reg_233[4:0];

assign trunc_ln1447_fu_921_p1 = ap_phi_mux_aExp_5_phi_fu_218_p4[4:0];

assign trunc_ln1448_fu_905_p1 = aSig_fu_900_p2[24:0];

assign trunc_ln1463_fu_795_p1 = b[7:0];

assign trunc_ln1472_fu_749_p1 = a[7:0];

assign trunc_ln1489_fu_1077_p1 = aSig_5_reg_205[22:0];

assign trunc_ln1493_fu_1222_p1 = zExp_fu_1216_p2[8:0];

assign trunc_ln482_2_fu_1415_p1 = float_exception_flags_1_i[3:0];

assign trunc_ln482_fu_1585_p1 = float_exception_flags_1_load_reg_1974[2:0];

assign trunc_ln780_fu_1493_p1 = float_exception_flags_1_loc_1_reg_288[4:0];

assign trunc_ln_fu_1447_p4 = {{add_ln781_fu_1441_p2[31:7]}};

assign xor_ln525_1_fu_1682_p2 = (icmp_ln488_4_reg_2256 ^ 1'd1);

assign xor_ln525_fu_1822_p2 = (icmp_ln488_2_reg_2324 ^ 1'd1);

assign xor_ln771_fu_1289_p2 = (tmp_35_fu_1261_p3 ^ 1'd1);

assign xor_ln779_fu_1507_p2 = (icmp_ln779_reg_2224 ^ 1'd1);

assign xor_ln782_fu_1467_p2 = (zext_ln782_fu_1463_p1 ^ 2'd3);

assign zExp_fu_1216_p2 = ($signed(sext_ln1493_fu_1212_p1) + $signed(sext_ln1489_fu_1169_p1));

assign zSig_3_fu_1189_p4 = {{{tmp_33_reg_2139}, {or_ln1492_fu_1177_p2}}, {1'd0}};

assign zSig_4_fu_1226_p3 = ((tmp_34_reg_2144[0:0] == 1'b1) ? zSig_fu_1182_p3 : zSig_3_fu_1189_p4);

assign zSig_fu_1182_p3 = {{tmp_reg_2134}, {or_ln1492_fu_1177_p2}};

assign zSign_fu_608_p2 = (tmp_26_fu_600_p3 ^ tmp_25_fu_573_p3);

assign z_11_fu_1327_p2 = ((zSig_4_fu_1226_p3 != 32'd0) ? 1'b1 : 1'b0);

assign z_fu_1382_p3 = {{tmp_5_reg_2209}, {or_ln135_fu_1377_p2}};

assign zext_ln129_fu_1307_p1 = sub_ln129_fu_1301_p2;

assign zext_ln135_fu_1348_p1 = add_ln135_fu_1343_p2;

assign zext_ln137_fu_1333_p1 = z_11_fu_1327_p2;

assign zext_ln1447_1_fu_596_p1 = bExp_fu_585_p4;

assign zext_ln1447_fu_569_p1 = aExp_fu_559_p4;

assign zext_ln1448_1_fu_555_p1 = aSig_6_fu_546_p1;

assign zext_ln1448_2_fu_581_p1 = bSig_6_fu_542_p1;

assign zext_ln1448_fu_551_p1 = aSig_6_fu_546_p1;

assign zext_ln1493_1_fu_1201_p1 = tmp_34_reg_2144;

assign zext_ln1493_fu_1198_p1 = tmp_34_reg_2144;

assign zext_ln445_1_fu_1026_p1 = shiftCount_9_fu_1019_p3;

assign zext_ln445_fu_876_p1 = shiftCount_5_fu_869_p3;

assign zext_ln449_1_fu_1000_p1 = select_ln445_2_fu_992_p3;

assign zext_ln449_fu_712_p1 = select_ln445_fu_704_p3;

assign zext_ln731_1_fu_1030_p1 = countLeadingZerosHigh_q0;

assign zext_ln731_fu_880_p1 = countLeadingZerosHigh_q0;

assign zext_ln782_fu_1463_p1 = icmp_ln782_fu_1457_p2;

always @ (posedge ap_clk) begin
    zext_ln1448_reg_1924[31:23] <= 9'b000000000;
    zext_ln1448_2_reg_1944[31:23] <= 9'b000000000;
    zext_ln1447_1_reg_1955[8] <= 1'b0;
    or_ln3_reg_1981[0] <= 1'b1;
end

endmodule //scaffold_fn_float32_mul
